app:
  "rapidApiUrl": "https://rapidapi.p.rapidapi.com"
  "rapidApiHost": "covid-19-data.p.rapidapi.com"
  "rapidApiHostHeader": "x-rapidapi-host"
  "rapidApiKeyHeader": "x-rapidapi-key"
  "rapidApiKey": "3704fdb777msh2b958a05da5591dp19bc74jsn0b77c46970bc"

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect